### ISSUE TITLE
How to add type annotations

### ISSUE THREAD

**Issue by itsfarseen** [Carotti/tagged-union#1]
```python
from tagged_union import tagged_union

@tagged_union
class Foo:
    A = int
    B = str

class Base:
    def foo(self) -> Foo:
        raise NotImplementedError()

class DerivedA(Base):
    def foo(self) -> Foo:
        return Foo.A(123)     # error occurs here
```

mypy is giving the following error on this:

```python
scratch-1.py:14: error: Incompatible return value type (got "int", expected "Foo")
```

What is the correct way to annotate types for `foo()`?

**Comment by itsfarseen** [comment]
Just found out that adding an `assert isinstance(..)` fixes mypy error:

```python
class DerivedA(Base):
    def foo(self) -> Foo:
        f = Foo.A(123)
        assert isinstance(f, Foo)
        return f   # no error here
```

**Comment by Carotti** [comment]
This is an interesting and important feature to support. I suspect the reason for this is the way in which mypy handles decorators, specifically when I am completely replacing the attributes of the `tagged_union` class such as `A` and `B`. I don't fully understand how mypy works with decorators but I will try to get this to work.

**Comment by Carotti** [comment]
Apparently, class decorators that modify a class (So most of them) are officially unsupported by mypy (see: https://github.com/python/mypy/wiki/Unsupported-Python-Features).

I still suspect there is a workaround somehow, possible using your `assert isinstance(...)` trick.
